name: push_to_mrt
inputs:
  CWD:
    description: Project directory
  TARGET:
    description: MRT target
  VERSION:
    description: Git SHA of the version being deployed
    required: true
runs:
  using: composite
  steps:
    - name: Push Bundle to MRT
      run: |-
        cd ${{ inputs.CWD }}
        project="scaffold-pwa"
        build="build ${{ github.run_id }} on ${{ github.ref }} (${{ inputs.VERSION }})"
        if [[ ${{ inputs.TARGET }} ]]; then
          npm run push -- -s $project --message "$build" --target ${{ inputs.TARGET }}
        fi
      shell: bash
