name: SalesforceCommerceCloud/pwa-kit/nightly_release
on:
  workflow_dispatch:
  push:
    branches:
      - "feature/nightly-releases"
  schedule:
    # Run every day at 12am (PST) - cron uses UTC times
    - cron: "0 8 * * *"

jobs:
  create_nightly_release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Get Timestamp
        run: |-
          echo "release_timestamp=$(date +'%m%d%Y%H%M%S')" >> "$GITHUB_ENV"

      - name: Get monorepo version
        run: |-
          version=`cat package.json | jq -r ".version" | cut -d "-" -f 1`
          echo "monorepo_version_base=$version" >> "$GITHUB_ENV"

      - name: Get retail-react-app version
        run: |-
          version=`cat packages/template-retail-react-app/package.json | jq -r ".version" | cut -d "-" -f 1`
          echo "retail_app_version_base=$version" >> "$GITHUB_ENV"
      
      - name: Get commerce-sdk-react version
        run: |-
          version=`cat packages/commerce-sdk-react/package.json | jq -r ".version" | cut -d "-" -f 1`
          echo "commerce_sdk_react_version_base=$version" >> "$GITHUB_ENV"
      
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: npm

      - name: Install Monorepo Dependencies
        run: |-
          # Install node dependencies
          node ./scripts/gtime.js monorepo_install npm ci
